/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GrupoC_Reto2;

/**
 *
 * @author ANGELO
 */
public class ConvertidorPrueba extends javax.swing.JFrame {

    Double binario, decimal, octal;
    String hexadecimal;

    public ConvertidorPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        kilometros = new javax.swing.JTextField();
        Binario = new javax.swing.JLabel();
        pulgadas = new javax.swing.JTextField();
        Octanal = new javax.swing.JLabel();
        yardas = new javax.swing.JTextField();
        Decimal = new javax.swing.JLabel();
        centimetros = new javax.swing.JTextField();
        Hexadecimal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        millas = new javax.swing.JTextField();
        Millas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kilometros.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        kilometros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kilometros.setText("0");

        Binario.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Binario.setText("Binario");

        pulgadas.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        pulgadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pulgadas.setText("0");

        Octanal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Octanal.setText("Octanal");

        yardas.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        yardas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yardas.setText("0");
        yardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardasActionPerformed(evt);
            }
        });

        Decimal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Decimal.setText("Decimal");

        centimetros.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        centimetros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        centimetros.setText("0");
        centimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centimetrosActionPerformed(evt);
            }
        });

        Hexadecimal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Hexadecimal.setText("Centimetros");

        jLabel1.setText("Conversor");

        jButton1.setText("Resetear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        millas.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        millas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        millas.setText("0");

        Millas.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Millas.setText("Binario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(millas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(centimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Binario)
                            .addComponent(kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Decimal)
                            .addComponent(yardas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Octanal)
                            .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hexadecimal)
                            .addComponent(Millas))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hexadecimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(centimetros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Decimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yardas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Octanal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Binario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kilometros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Millas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(millas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
//Hexadecimal
        double cent,yar,pul,kil,mil,r1,r2,r3,r4;
        
        cent=Integer.parseInt(centimetros.getText());
        yar=Integer.parseInt(yardas.getText());
        pul=Integer.parseInt(pulgadas.getText());
        kil=Integer.parseInt(kilometros.getText());       
        mil=Integer.parseInt(millas.getText());
        //centimetros
        if (cent!=0 && yar==0 && pul==0 && kil==0 && mil==0){
            r1=cent/91.44;
            r2=cent/2.54;
            r3=cent/100000;
            r4=cent/160934.4;
            yardas.setText(""+r1);
            pulgadas.setText(""+r2);
            kilometros.setText(""+r3);
            millas.setText(""+r4);
            
        }
        //yardas
        if (cent==0 && yar!=0 && pul==0 && kil==0 && mil==0){
            r1=yar*91.44;
            r2=yar*36;
            r3=yar/1093.613;
            r4=yar/1760;
            centimetros.setText(""+r1);
            pulgadas.setText(""+r2);
            kilometros.setText(""+r3);
            millas.setText(""+r4);
            
        }
        if (cent==0 && yar==0 && pul!=0 && kil==0 && mil==0){
            r1=yar*91.44;
            r2=yar*36;
            r3=yar/1093.613;
            r4=yar/1760;
            centimetros.setText(""+r1);
            pulgadas.setText(""+r2);
            kilometros.setText(""+r3);
            millas.setText(""+r4);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void centimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centimetrosActionPerformed
//        hexadecimal= Double.parseDouble(jTextHexadecimal.getText());
    }//GEN-LAST:event_centimetrosActionPerformed

    private void yardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardasActionPerformed
        decimal= Double.parseDouble(yardas.getText());
    }//GEN-LAST:event_yardasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Binario;
    private javax.swing.JLabel Decimal;
    private javax.swing.JLabel Hexadecimal;
    private javax.swing.JLabel Millas;
    private javax.swing.JLabel Octanal;
    private javax.swing.JTextField centimetros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kilometros;
    private javax.swing.JTextField millas;
    private javax.swing.JTextField pulgadas;
    private javax.swing.JTextField yardas;
    // End of variables declaration//GEN-END:variables
}
