/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GrupoC_Reto2;

/**
 *
 * @author ANGELO
 */
public class RifaCovid extends javax.swing.JFrame {

    /**
     * Creates new form RifaCovid
     */
    public RifaCovid() {
        initComponents();
         setResizable(true);
        setSize(1150, 553);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextoGanador6 = new javax.swing.JLabel();
        TituloGanador6 = new javax.swing.JLabel();
        TituloGanador8 = new javax.swing.JLabel();
        TextoGanador8 = new javax.swing.JLabel();
        TextoGanador9 = new javax.swing.JLabel();
        TituloGanador10 = new javax.swing.JLabel();
        TextoGanador10 = new javax.swing.JLabel();
        TextoGanador7 = new javax.swing.JLabel();
        TituloGanador7 = new javax.swing.JLabel();
        BotonSorteo = new javax.swing.JButton();
        TituloGanador5 = new javax.swing.JLabel();
        G5 = new javax.swing.JLabel();
        G4 = new javax.swing.JLabel();
        TituloGanador4 = new javax.swing.JLabel();
        G3 = new javax.swing.JLabel();
        TituloGanador3 = new javax.swing.JLabel();
        G2 = new javax.swing.JLabel();
        TituloGanador2 = new javax.swing.JLabel();
        G1 = new javax.swing.JLabel();
        TituloGanador1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelIMAGEN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PREMIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        TextoGanador6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TextoGanador6.setForeground(new java.awt.Color(255, 255, 255));
        TextoGanador6.setText("UNA MOTO");
        getContentPane().add(TextoGanador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 177, -1));

        TituloGanador6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TituloGanador6.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador6.setText("GANADOR1");
        getContentPane().add(TituloGanador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 177, -1));

        TituloGanador8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TituloGanador8.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador8.setText("GANADOR2");
        getContentPane().add(TituloGanador8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 177, -1));

        TextoGanador8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TextoGanador8.setForeground(new java.awt.Color(255, 255, 255));
        TextoGanador8.setText("COCINA ELECTRICA");
        getContentPane().add(TextoGanador8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 177, -1));

        TextoGanador9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TextoGanador9.setForeground(new java.awt.Color(255, 255, 255));
        TextoGanador9.setText("MICROONDAS");
        getContentPane().add(TextoGanador9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 177, -1));

        TituloGanador10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TituloGanador10.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador10.setText("GANADOR  4");
        getContentPane().add(TituloGanador10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 177, -1));

        TextoGanador10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TextoGanador10.setForeground(new java.awt.Color(255, 255, 255));
        TextoGanador10.setText(" 2 BOLETOS AL CINE");
        getContentPane().add(TextoGanador10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 177, -1));

        TextoGanador7.setBackground(new java.awt.Color(255, 255, 255));
        TextoGanador7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TextoGanador7.setForeground(new java.awt.Color(255, 255, 255));
        TextoGanador7.setText("5 PAQUETES DE MASCARILLAS KN95");
        getContentPane().add(TextoGanador7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, -1, -1));

        TituloGanador7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TituloGanador7.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador7.setText("GANADOR  5");
        getContentPane().add(TituloGanador7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 177, -1));

        BotonSorteo.setBackground(new java.awt.Color(255, 255, 255));
        BotonSorteo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        BotonSorteo.setText("COMENZAR RIFA !!");
        BotonSorteo.setContentAreaFilled(false);
        BotonSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSorteoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSorteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 290, 87));

        TituloGanador5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TituloGanador5.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador5.setText("GANADOR 5");
        getContentPane().add(TituloGanador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 440, -1));

        G5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        G5.setForeground(new java.awt.Color(255, 255, 255));
        G5.setText("000000");
        G5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                G5AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 570, -1));

        G4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        G4.setForeground(new java.awt.Color(255, 255, 255));
        G4.setText("000000");
        getContentPane().add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 440, -1));

        TituloGanador4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TituloGanador4.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador4.setText("GANADOR 4");
        getContentPane().add(TituloGanador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 156, -1));

        G3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        G3.setForeground(new java.awt.Color(255, 255, 255));
        G3.setText("000000");
        getContentPane().add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 440, -1));

        TituloGanador3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TituloGanador3.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador3.setText("GANADOR 3");
        getContentPane().add(TituloGanador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 156, -1));

        G2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        G2.setForeground(new java.awt.Color(255, 255, 255));
        G2.setText("000000");
        getContentPane().add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 440, -1));

        TituloGanador2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TituloGanador2.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador2.setText("GANADOR 2");
        getContentPane().add(TituloGanador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 156, -1));

        G1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        G1.setForeground(new java.awt.Color(255, 255, 255));
        G1.setText("000000");
        getContentPane().add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 440, -1));

        TituloGanador1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TituloGanador1.setForeground(new java.awt.Color(255, 255, 255));
        TituloGanador1.setText("GANADOR 1");
        getContentPane().add(TituloGanador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 156, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GRAN RIFA COVID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabelIMAGEN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelIMAGEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GrupoC_Reto2/ImagenCovid.jpg"))); // NOI18N
        jLabelIMAGEN.setPreferredSize(new java.awt.Dimension(1500, 720));
        getContentPane().add(jLabelIMAGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -230, 1290, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSorteoActionPerformed
        
        //variables, en donde se puede cambiar el maximo y minimo del numero generado
        int NumeroMaximoDeLaRifa = 200;
        int NumeroMinimoDeLaRifa = NumeroMaximoDeLaRifa/2;//10 para dos cifras, 100 para 3 cifras, 1000 para 4 cifras y asi sucesivamente
        
        //NO SE PUEDEN COLOCAR DEBAJO DE LOS G1, G2, G3...
        int g1 = (int) (Math.random() * NumeroMaximoDeLaRifa + NumeroMinimoDeLaRifa);
        //GANADOR 2, NUMERO DIFERENTE AL 1
        int g2 = (int) (Math.random() * NumeroMaximoDeLaRifa + NumeroMinimoDeLaRifa);
        
        int g3 = (int) (Math.random() * NumeroMaximoDeLaRifa + NumeroMinimoDeLaRifa);
        
        int g4 = (int) (Math.random() * NumeroMaximoDeLaRifa + NumeroMinimoDeLaRifa);
        
        int g5 = (int) (Math.random() * NumeroMaximoDeLaRifa + NumeroMinimoDeLaRifa);
        
        //Math.random genera un numero aleatorio 
        //Eliminar los valores ingresados anteriormente.
        G1.setText(
            "000" + (""));

        G2.setText(
            "000" + (""));
        //        G1.setText("000" + (Integer.toString((int) (Math.random() * 3))));
        G3.setText(
            "000" + (""));
        G4.setText(
            "000" + (""));
        G5.setText(
            "000" + (""));
        
        //GRACIAS A ESTO NO SE REPETIRAN LOS NUMEROS ALEATORIOS
        if (g1 == g2) {
            return;//SI g2 es igual al alterior, se volvera a ejecutar hasta ser diferente
        }

        //GANADOR 3, NUMERO DIFERENTE AL 1 Y 2
        
        if (g3 == g1 || g3 == g2) {
            return;//SI g3 es igual a los alteriores, se volvera a ejecutar hasta ser diferente
        }

        //GANADOR 4, NUMERO DIFERENTE AL 1, 2 Y 3
        
        if (g4 == g1 || g4 == g2 || g4 == g3) {
            return;//SI g4 es igual a los alteriores, se volvera a ejecutar hasta ser diferente
        }

        
        if (g5 == g1 || g5 == g2 || g5 == g3 || g5 == g4) {
            return;//SI g5 es igual a los alteriores, se volvera a ejecutar hasta ser diferente
        }
        //AQUI SE ALMACENA LOS RESULTADOS CORRESPONDIENTES, SE LE AGREGA "000" POR QUE LA
        G1.setText(
            "000" + (Integer.toString(g1) + "           GANÓ UNA MOTO!"));

        G2.setText(
            "000" + (Integer.toString(g2)) + "          GANÓ UNA COCINA ELECTRICA!");
        //        G1.setText("000" + (Integer.toString((int) (Math.random() * 3))));
        G3.setText(
            "000" + (Integer.toString(g3))+ "          GANÓ UN MICROONDAS!");
        G4.setText(
            "000" + (Integer.toString(g4))+ "          GANÓ DOS BOLETOS AL CINE!");
        G5.setText(
            "000" + (Integer.toString(g5))+ "          GANÓ 5 PAQUETES DE MASCARILLAS KN95!");

    }//GEN-LAST:event_BotonSorteoActionPerformed

    private void G5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_G5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_G5AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RifaCovid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RifaCovid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RifaCovid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RifaCovid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RifaCovid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSorteo;
    private javax.swing.JLabel G1;
    private javax.swing.JLabel G2;
    private javax.swing.JLabel G3;
    private javax.swing.JLabel G4;
    private javax.swing.JLabel G5;
    private javax.swing.JLabel TextoGanador10;
    private javax.swing.JLabel TextoGanador6;
    private javax.swing.JLabel TextoGanador7;
    private javax.swing.JLabel TextoGanador8;
    private javax.swing.JLabel TextoGanador9;
    private javax.swing.JLabel TituloGanador1;
    private javax.swing.JLabel TituloGanador10;
    private javax.swing.JLabel TituloGanador2;
    private javax.swing.JLabel TituloGanador3;
    private javax.swing.JLabel TituloGanador4;
    private javax.swing.JLabel TituloGanador5;
    private javax.swing.JLabel TituloGanador6;
    private javax.swing.JLabel TituloGanador7;
    private javax.swing.JLabel TituloGanador8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIMAGEN;
    // End of variables declaration//GEN-END:variables

}
